---
name: 'Generate Pull Request Title and Description'
description: 'Generate Pull Request Title and Description'
author: 'Takeru O'oyama @tqer39'
branding:
  color: 'blue'
  icon: 'terminal'
runs:
  using: 'composite'
  steps:
    - run: echo "hoge"
      shell: bash
