---
name: OpenIA Generate PR Description

on:
  pull_request:
    branches:
      - main

jobs:
  generate-pr-description:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    if: contains(github.event.pull_request.user.login, 'renovate') == false
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 全ての履歴を取得するように設定

      - name: Set up Python
        uses: actions/setup-python@v5

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          version: "0.4.26"

      - name: Generate PR Title and Description
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_MODEL: "gpt-4o"
        run: |
          uv run scripts/generate_pr_description.py > pr_output.txt
          cat pr_output.txt

      - name: Update PR Title and Description
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PR_NUMBER=${{ github.event.pull_request.number }}
          PR_TITLE=$(head -n 1 pr_output.txt)
          PR_BODY=$(tail -n +2 pr_output.txt)
          gh pr edit $PR_NUMBER --title "$PR_TITLE" --body "$PR_BODY"
